// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBW1hwv9GaU8sMbdFY9pPwDvNjpkC3D-D8',
    appId: '1:679183492138:web:854737a460ec2626130f53',
    messagingSenderId: '679183492138',
    projectId: 'social-media-narrator',
    authDomain: 'social-media-narrator.firebaseapp.com',
    storageBucket: 'social-media-narrator.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqBStdy_Fzp2SJiu_GXopImpcm4P4Oz90',
    appId: '1:679183492138:android:5041e2fe235e4a67130f53',
    messagingSenderId: '679183492138',
    projectId: 'social-media-narrator',
    storageBucket: 'social-media-narrator.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYzPEoNDIzg23HOkt8DIL8SNPauFrCBKU',
    appId: '1:679183492138:ios:6401b3aa1ba46c84130f53',
    messagingSenderId: '679183492138',
    projectId: 'social-media-narrator',
    storageBucket: 'social-media-narrator.appspot.com',
    iosBundleId: 'com.example.socialMediaNarrator',
  );

}